server:
  port: 8089
#  context-path: /wmz
  error:
    path: /error

spring:
  http:
      multipart:
        max-file-size: 500Mb
        max-request-size: 500Mb

uploadPath: E:/FileServer/
videoPath: E:/FileServer/Video/
imagePath: E:/FileServer/Image/
virtualPath: E:/FileServer/Virtual/
documentPath: E:/FileServer/Document/
audioPath: E:/FileServer/Audio/
