server:
  port: 80
  context-path: /wmz
  error:
    path: /error

spring:
  thymeleaf:
    cache: false #关闭缓存，及时刷新,生产环境建议打开
    encoding: UTF-8
  devtools:
    restart:
      enabled: true
#      additional-paths: src/main
  mvc:
    static-path-pattern:
